---
title: "Beaver_dispersal_model_Flanders"
author: 
- "Frank Huysentruyt, Research Institute for Nature and Forest (INBO)"
- "Robrecht Dockx, Research Institute for Nature and Forest (INBO)""
date: "2025-09-03"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tidyverse)#general environment
library(raster)#read raster data
library(SiMRiv)#simulate movements
library(leaflet)#maps
library(sf)#simple features
```

## Introduction

This code describes a model that simulates movements of beavers starting from point locations (known territories) in Flanders. For input, it uses the raster output of a Maxent model (projection_wide) for Flanders and surrounding 10km buffer as a habit suitability layer. It also u

```{r read data, include = FALSE}
##Read habitat suitability layer
suitability <- raster("./Input/projection_wide.tif")

##Read UTM layer (1*1 km squares)
UTM1 <- st_read("./Input/Vlaanderen_UTM.shp") %>% 
    st_transform(crs = 4326)

##Read layer with known beaver territories in Flanders in 2024
##These points are used as starting points for beaver movement
terr_2024 <- st_read("./Input/Beaver_territories_2024.shp") %>%
  st_transform(crs = 4326)

##Read layer with larger rivers, relevant for beaver dispersal
shape_riv <- st_read("./Input/Shape_RIV.shp") %>% 
  st_transform(crs = 25831)

##Refine suitability raster and transform suitability to unsuitability according to the relation described by Carroll (2020)
unsuitability <- disaggregate(suitability, fact = 2)
unsuitability@data@values <- (100-99*((1-exp(-1*unsuitability@data@values))/(1-exp(-1))))/100
unsuitability <- projectRaster(unsuitability, crs = crs(shape_riv))

##Create Resistance layer
##Combine unsuitability with rivers (with a 200m buffer) and transform to landscape resistance layer
river_buf <- st_buffer(st_as_sf(shape_riv), dist = 200)# 200 m buffer
river_buf_sp <- as(river_buf, "Spatial")# Convert buffer back to Spatial for raster::rasterize
riv_ras <- rasterize(river_buf_sp, unsuitability, field = 1, background = NA)# Rasterize onto base grid
resistance <- unsuitability# Build resistance layer
resistance[!is.na(riv_ras[])] <- 0.05  # give rivers low resistance value
```

## Including Plots

You can also embed plots, for example:

```{r define walker, eval = FALSE}

set.seed(12345)
dummy_start <- sample(terr_2024$geometry, 5)#dummy with 5 starting points for demo

init_dummy_all <- dummy_start %>% 
  st_transform(crs = 25831)
init_dummy_all <- st_coordinates(init_dummy_all)

##Define walker
levy.walker <- (species(state.RW() + state.CRW(0.98), trans = transitionMatrix(0.1, 0.1)) + 40)*1000

totaal <- NULL
allpoints <- st_as_sf(data.frame("x" = init_dummy_all[,1],
                                  "y" = init_dummy_all[,2], run = 0, 
                                  year = 0),
                       coords = c("x", "y"), crs = 25831)

```

```{r model functions, eval = FALSE}
simulate_row <- function(X, Y, levy.walker, resistance, suitraster, steps, init_dummy_all) {
  # Select starting coordinates
  coords <- matrix(c(X, Y), nrow = 1, ncol = 2)

  k <- 0
  t <- 0
  while (rbinom(1,1,t)==0 & k < 3) {  # Simulate max 3 times
    sim_nieuw <- simulate(levy.walker, steps, resist = resistance, coords = coords)
    last_point <- sim_nieuw[steps, 1:2]  # Last point of simulation

    # Convert last point to sf object
    point <- st_as_sf(data.frame(x = last_point[1], y = last_point[2]),
                     coords = c("x", "y"), crs = 25831)

    # Check if it intersects with suitability raster
    joined <- st_join(point, suitraster, join = st_intersects)
    t <- ifelse(is.na(joined[[1]]), 0, joined[[1]])  # Check intersection result

    k <- k + 1
  }

  # Only return valid points
  if (k<3) {

    intersection <- st_intersects(point, suitraster, sparse = FALSE)
    intersected_rows <- apply(intersection, 1, function(x) which(x))
    p <- as.numeric(unlist(intersected_rows))
    suitraster$projection_random[p] <- ifelse(suitraster$projection_random[p]>0.1,
                                              suitraster$projection_random[p]-0.1,
                                              suitraster$projection_random[p])
    return(point)
  } else {
    return(NULL)
  }
}


randomRows = function(df,n){
  return(df[sample(nrow(df),n, replace = TRUE),])
}
```

```{r model, eval = FALSE}

suitraster <-  st_as_sf(rasterToPolygons(suitability))
suitraster_base <- suitraster %>%  st_transform(crs = 25831)
allpoints_init <- allpoints

#Dispersal model define number of model runs (z)
for (z in 1:2) {

  suitraster <- suitraster_base
  allpoints <- allpoints_init

  init_dummy <- as.data.frame(init_dummy_all)  # Copy of dataset

  for (i in 1:3) { # model over 3 years

    num_samples <- ceiling(nrow(init_dummy_all) * (1.21^i))

    init_dummy <- randomRows(init_dummy, num_samples )

  points <- init_dummy %>%
    rowwise() %>%
    mutate(point = list(simulate_row(
      X = X,
      Y = Y,
      levy.walker = levy.walker,
      resistance = resistance,
      suitraster = suitraster,
      steps = 60000,
      init_dummy_all = init_dummy
    ))) %>%
    ungroup()
  
  points <- bind_rows(points$point)
  
  points <- data.frame(run = z,
                       geometry = points$geometry)
  
  points <- st_as_sf(data.frame(geometry = points$geometry,
                                     run = z,
                                year = i),
                          crs = 25831)

  allpoints <- bind_rows(allpoints, points)
  
  points_no_geo <- points %>% 
  st_drop_geometry()  %>% 
    mutate(X = st_coordinates(points)[,1],
           Y = st_coordinates(points)[,2]) %>% 
    dplyr::select(X, Y)
  
  init_dummy <- rbind(init_dummy, points_no_geo)

  }
  
saveRDS(allpoints, paste0("./Output/allpoints_", z, ".RDS"))
  
}

```

```{r read_in_data1}

data <- file.path("./Output/")

rds_files <- list.files(data, pattern = "\\.RDS$", full.names = TRUE)

data_rds <- do.call(rbind, lapply(rds_files, readRDS))

data_first <- data_rds %>% filter(run == 0 & year == 0) %>% 
  distinct(geometry, .keep_all = TRUE)

data_second <- data_rds %>% filter(run != 0)

data_rds <- rbind(data_first, 
                  data_second)

```

```{r plot1}

points_mod <- data_rds %>%
  st_transform(crs = 4326)
tmp <- st_join(points_mod, UTM1, join = st_intersects) %>%
  group_by(TAG) %>%
  summarise(number = length(TAG)) %>%
  st_drop_geometry()

Shape_mod_dummy <- merge(UTM1, tmp, by='TAG', all.x=T) %>%
  mutate(number = replace_na(number,0))

Shape_mod_dummy$Probability <- cut(Shape_mod_dummy$number,
                                      breaks = c(0,1,5,20,Inf),
                                      labels = c("Accidental","Low",
                                                 "Middle","High"), 
                                      include_lowest = TRUE, 
                                      right = FALSE)

factpal <- colorFactor(heat.colors(4), Shape_mod_dummy$Probability, 
                       reverse=T)

map <- leaflet(subset(Shape_mod_dummy, number > 0)) %>%
  addTiles() %>%
  addPolygons(color = ~factpal(Probability),
              opacity=0,
              fillOpacity=0.8) %>%
  addLegend(pal = factpal, values = ~Probability)

map

```